# Terraform
alias tfa='terraform apply -auto-approve'
alias tfat='terraform apply -auto-approve -target $(terraform state list | fzf -m --height 20%)'
alias tfad='terraform destroy -auto-approve -target $(terraform state list | fzf -m --height 20%)'
alias tfd='terraform destroy -auto-approve'
alias tfi='terraform init -reconfigure'
alias tfp='terraform plan'
alias tfr='terraform refresh'
alias tft='terraform taint $(terraform state list | fzf -m --height 20%)'
alias tf='terraform'
alias tfs='terraform state'
alias tfsl='terraform state list'
alias tfsr='terraform state rm $(terraform state list | fzf -m --height 20%)'
