#!/bin/bash
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-completions" ]
then 
  echo "Installing zsh-completions plugin..."  
  git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

