#! /bin/sh
pgrep -x sxhkd -c $HOME/.config/sxhkd/common.sxhkd $HOME/.config/sxhkd/bspwm.sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/common.sxhkd $HOME/.config/sxhkd/bspwm.sxhkd &

bspc monitor -d dev term web music coms

bspc config border_width        1
bspc config window_gap          5

# Theme
bspc config normal_border_color   "#44475a"
bspc config active_border_color   "#6272a4"
bspc config focused_border_color  "#8be9fd"
bspc config presel_feedback_color "#6272a4"

bspc config pointer_follows_monitor true

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true
