#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkdrc -c $HOME/.config/sxhkdrc &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

bspc config border_width   2
bspc config window_gap     15

bspc config borderless_monocle      true
bspc config pointer_follows_monitor true
bspc config gapless_monocle         false
bspc config single_monocle          true
bspc config split_ratio             0.50

bspc rule -a firefox desktop='^2'
bspc rule -a chromium desktop='^3'
bspc rule -a Zathura state=tiled
bspc rule -a screenkey manage=off


feh --bg-scale $HOME/pics/wallpaper/minimal_forest.jpg
